language: scala

jdk:
  - openjdk8

stages:
  - name: test

jobs:
  include:
    - env: TEST="build"
      script: sbt headerCheck compile test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

